export enum DatabaseModelNames {
  User = "User",
  Organization = "Organization",
  OrgInvitation = "OrgInvitation",
  Folder = "Folder",
  Log = "Log",
  FavoriteFolder = "FavoriteFolder",
  LastCheckedFolder = "LastCheckedFolder",
  FolderPreference = "FolderPreference",
  Rule = "Rule",
  Integration = "Integration",
  OAuthRequest = "OAuthRequest",
  PendingSlackInstallation = "PendingSlackInstallation",
  Funnel = "Funnel",
  FunnelCompletion = "FunnelCompletion",
  Dashboard = "Dashboard",
  Widget = "Widget",
}
